export const Colors = {
  background: '#0A0A0F',
  surface: '#141419',
  surfaceLight: '#1E1E26',
  surfaceLighter: '#2A2A35',
  accent: '#007AFF',
  accentDark: '#0055CC',
  accentLight: '#3399FF',
  accentGlow: 'rgba(0, 122, 255, 0.3)',
  accentGlowStrong: 'rgba(0, 122, 255, 0.5)',
  electricBlue: '#00D4FF',
  electricBlueGlow: 'rgba(0, 212, 255, 0.3)',
  success: '#34C759',
  successGlow: 'rgba(52, 199, 89, 0.3)',
  warning: '#FF9F0A',
  warningGlow: 'rgba(255, 159, 10, 0.3)',
  warningAmber: '#FFB800',
  warningAmberGlow: 'rgba(255, 184, 0, 0.3)',
  danger: '#FF3B30',
  dangerGlow: 'rgba(255, 59, 48, 0.3)',
  purple: '#AF52DE',
  purpleGlow: 'rgba(175, 82, 222, 0.3)',
  cyan: '#32D7E0',
  cyanGlow: 'rgba(50, 215, 224, 0.3)',
  textPrimary: '#FFFFFF',
  textSecondary: '#A0A0B0',
  textTertiary: '#5A5A6E',
  border: '#1E1E2A',
  borderLight: '#2A2A3A',
  overlay: 'rgba(0, 0, 0, 0.7)',
  cardShadow: 'rgba(0, 0, 0, 0.5)',
  inactive: '#3A3A48',
  // Release Optimization colors
  gold: '#FFD700',
  goldGlow: 'rgba(255, 215, 0, 0.3)',
  goldDark: '#B8860B',
  verifiedGreen: '#00E676',
  verifiedGreenGlow: 'rgba(0, 230, 118, 0.3)',
  emerald: '#50C878',
  emeraldGlow: 'rgba(80, 200, 120, 0.3)',
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const BorderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  full: 9999,
};

export const FontSize = {
  xs: 10,
  sm: 12,
  md: 14,
  lg: 16,
  xl: 18,
  xxl: 22,
  xxxl: 28,
  display: 34,
};

export const STORAGE_KEYS = {
  HOOK_ENABLED: 'virtucam_hook_enabled',
  FRONT_CAMERA: 'virtucam_front_camera',
  BACK_CAMERA: 'virtucam_back_camera',
  SELECTED_MEDIA: 'virtucam_selected_media',
  RECENT_FILES: 'virtucam_recent_files',
  SCALE_MODE: 'virtucam_scale_mode',
  ROTATION: 'virtucam_rotation',
  MIRRORED: 'virtucam_mirrored',
  FLIPPED_VERTICAL: 'virtucam_flipped_vertical',
  OFFSET_X: 'virtucam_offset_x',
  OFFSET_Y: 'virtucam_offset_y',
  LOOP_START: 'virtucam_loop_start',
  LOOP_END: 'virtucam_loop_end',
  LOOP_ENABLED: 'virtucam_loop_enabled',
  AI_OPTIMIZE: 'virtucam_ai_optimize',
  AI_SUBJECT_LOCK: 'virtucam_ai_subject_lock',
  ENGINE_ACTIVE: 'virtucam_engine_active',
  FLOATING_BUBBLE: 'virtucam_floating_bubble',
  TARGET_APPS: 'virtucam_target_apps',
  TARGET_MODE: 'virtucam_target_mode',
  AI_ENHANCEMENT: 'virtucam_ai_enhancement',
  ONBOARDING_COMPLETE: 'virtucam_onboarding_complete',
  SYSTEM_STATUS: 'virtucam_system_status',
  CONFIG_BRIDGE: 'virtucam_config_bridge',
  ENHANCED_MEDIA_CACHE: 'virtucam_enhanced_media_cache',
  HOOK_SESSION_LOG: 'virtucam_hook_session_log',
  ENGINE_INITIALIZED: 'virtucam_engine_initialized',
  INJECTION_METHOD: 'virtucam_injection_method',
  CAMERA2_HOOK: 'virtucam_camera2_hook',
  CAMERA1_HOOK: 'virtucam_camera1_hook',
  VIRTUAL_LOOPBACK: 'virtucam_virtual_loopback',
  SETUP_WIZARD_COMPLETE: 'virtucam_setup_wizard_complete',
  // Release Optimization keys
  INTEGRITY_SCAN_RESULT: 'virtucam_integrity_scan_result',
  INTEGRITY_LAST_SCAN: 'virtucam_integrity_last_scan',
  SYSTEM_REPORT_LOG: 'virtucam_system_report_log',
  ANDROID_VERSION_DETECTED: 'virtucam_android_version_detected',
  COMPATIBILITY_MODE: 'virtucam_compatibility_mode',
  BATTERY_OPTIMIZED: 'virtucam_battery_optimized',
  AI_CACHE_DATA: 'virtucam_ai_cache_data',
  AI_CACHE_TIMESTAMP: 'virtucam_ai_cache_timestamp',
  ADAPTIVE_LAYOUT_RATIO: 'virtucam_adaptive_layout_ratio',
  ONBOARDING_V2_COMPLETE: 'virtucam_onboarding_v2_complete',
};
